### ISSUE TITLE
NameError: uninitialized constant Capistrano::EnvConfig

### ISSUE THREAD

**Issue by tenshiAMD** [itay-grudev/capistrano-env_config#5]
It seems not working when using Ruby 3.0. It is always throwing an error

```
NameError: uninitialized constant Capistrano::EnvConfig
```

**Comment by tenshiAMD** [comment]
nevermind. I forgot the add `require 'capistrano/env_config` in Capfile. 😅

**Comment by itay-grudev** [comment]
I'm positively surprised this project is still useful to someone.
